apiVersion: bashketchum02.github.io/v1alpha1
kind: PostgresDB
metadata:
  name: my-postgres
  namespace: default
spec:
  version: "16"
  replicas: 1
  storage: "1Gi"
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  backup:
    enabled: false
    schedule: "0 2 * * *"
    retentionDays: 7
